version: '3.9'

services:
    php:
      build: .
      ports: 
        - 80:80
        - 443:443
      volumes: 
        - ./www:/var/www/html
      links: 
        - db
        
      depends_on: 
        - db      
    db:
      image: mysql:5.7
      expose: 
        - 3306
      ports: 
        - 3306:3306
      volumes: 
        - /var/lib/mysql
      environment: 
        - MYSQL_ROOT_DATABASE=bancoteste
        - MYSQL_ROOT_PASSWORD=passroot 
